services:
  web:
    container_name: laboratories-exams_nestjs
    build: docker/dev
    ports:
      - "3333:3333"
      - "7001:7001"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - postgres

  postgres:
    container_name: laboratories-exams_postgres
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_DB=laboratories-exams_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_test:
    container_name: laboratories-exams_postgres_test
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_DB=laboratories-exams_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"
